### ISSUE TITLE
this was fun!

### ISSUE THREAD

**Issue by RetroNick2020** [Sparcie/Bobsfury#1]
I just started playing this and it's really fun. And I love the sounds also! Excellent!
How do I kill the snails?

**Comment by Sparcie** [comment]
Hi Nick,

Thanks for playing and offering some feedback :-). Some of the enemies such as the snails require using other weapons. The snails are killed by the grenades which you collect in crates. The default key for dropping one is G. There are also lightning bolts you can get from pick-ups that look like batteries. The key to change weapon is N by default.

Andrew
